### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by maxmcd** [stepfunc/dnp3#111]
Hello, sorry if this is the wrong venue for this type of ask. We're currently evaluating using this lib or the c++ version (we've previously implemented a DNP3 integration using the c++ lib). Is this project at the point where we could consider using it in production?

**Comment by jadamcrain** [comment]
It's almost ready for an initial release. We were just chatting this morning that we may be able to do it late next week. There are only a handful of items left:

https://github.com/stepfunc/dnp3/projects/1

We don't have a C++ backend yet for the code generator, so you'd unfortunately be using the C API. You can check out the example programs here:

https://github.com/stepfunc/dnp3/tree/master/ffi/bindings/c

I'd like to have a C++ back-end later this year, but since the C API is usable from C++ it hasn't been as high a priority for us as our C# and Java backends.

Documentation is still a WIP in the `/guide` folder, and will be completed after our first tagged release. We're doing integration projects ATM with two early adopters so we need have to start doing official releases ASAP even if it precedes the full documentation.

If you have any other questions please send an email to info@stepfunc.io and I will follow up from my address.

**Comment by maxmcd** [comment]
Thanks so much for the fast and complete response @jadamcrain.

Just asking here in case others are interested: I assume if we're down to write Rust the lib is good to use directly instead of through the c bindings?

**Comment by jadamcrain** [comment]
Absolutely, although we don't plan on publishing it to crates.io just yet so you'd have to use it as a git dependency for a bit.
