### ISSUE TITLE
Integrate aarch64 support into JAR release

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#136]
1. Detect if the Processor class is null, print a helpful message to stderr, and call exit() or throw the message via exception.

2. Use environment variable(s) as a workaround for platforms that where Processor is null. 

3. Include the aarch64 library inside the JAR. It makes the JAR a little bigger but aarch64 will probably be the most popular architecture after x64 Windows/Linux.

thoughts?

**Comment by emgre** [comment]
I'll try my initial thought of the other day to try loading each native library until one does not throw an exception, and perhaps avoid the whole `SystemUtils` check. The algorithm would be:
- If an env variable is set, then load this native library. Do not try anything else.
- Otherwise, try each native library until one does not throw an exception. If none succeeds, then throw an exception explaining the problem.

I'll also have to update the CI pipeline to generate the aarch64 binaries. It currently only generates the C bindings, not the Java ones. I'll only do it for Linux for now, I'm not sure where the Rust aarch64 support is for Windows atm.

Also, adding .NET support is probably not a big deal neither, I'll check it out.
