### ISSUE TITLE
Invalid ELF header (Possible cause: endianness mismatch)

### ISSUE THREAD

**Issue by j-pennington** [stepfunc/dnp3#177]
Hello,

I'm running into the following issue after upgrading from `0.9.1` to `0.10.0`; I'm using the java bindings.

# Expected Behavior
Minor version upgrade does not affect OS-compatibility

# Current Behavior
Version `0.10.0` java bindings apparently rely on `dnp3_ffi_java729936836377385741.dll`, even in a Linux environment.

# Context (Environment)
Docker container from `debian:stretch-slim` [base](https://hub.docker.com/_/debian).

Application running without error with 0.9.1:
```
        <dependency>
            <groupId>io.stepfunc</groupId>
            <artifactId>dnp3</artifactId>
            <version>0.9.1</version>
        </dependency>
```
Changing the version to 0.10.0 results in the following error at run time:
```
Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/dnp3_ffi_java729936836377385741.dll: /tmp/dnp3_ffi_java729936836377385741.dll: invalid ELF header (Possible cause: endianness mismatch)
```

Thank you for your time.

**Comment by emgre** [comment]
This is due to a change regarding how we load the native library. 0.9.1 used to try to figure out the running architecture and load the appropriate native library. This turned out to be unreliable as some platforms don't properly report the proper values. Therefore, we decided to try loading each packaged native library until one succeeds. However, we later found out that different JVM implementations throw different exceptions, including errors that don't inherit from `java.lang.Exception` when they are unable to load a native library.

It was reported in a more recent alpha release and fixed in the `main` branch that will become the future 1.0.0 version.

**Comment by j-pennington** [comment]
Thank you @emgre, closing this issue since it's already fixed in `main`

**Comment by jadamcrain** [comment]
@j-pennington How's it going with the library in general. If you have questions while evaluating it feel free to reach out to `info@stepfunc.io` and we can help via email.
