### ISSUE TITLE
feature request: configurable connect timeout

### ISSUE THREAD

**Issue by kevinherron** [stepfunc/dnp3#244]
I'm seeing connect timeouts that are ~75s by default, at least on macOS. It would be nice if this were configurable instead.

```
Nov 22 15:42:46.857  WARN dnp3-master-tcp{endpoint="10.20.4.74:20000"}: failed to connect to 10.20.4.74:20000: Operation timed out (os error 60) - waiting 1000 ms to retry
Nov 22 15:44:02.860  WARN dnp3-master-tcp{endpoint="10.20.4.74:20000"}: failed to connect to 10.20.4.74:20000: Operation timed out (os error 60) - waiting 2000 ms to retry
Nov 22 15:45:19.862  WARN dnp3-master-tcp{endpoint="10.20.4.74:20000"}: failed to connect to 10.20.4.74:20000: Operation timed out (os error 60) - waiting 4000 ms to retry
Nov 22 15:46:38.865  WARN dnp3-master-tcp{endpoint="10.20.4.74:20000"}: failed to connect to 10.20.4.74:20000: Operation timed out (os error 60) - waiting 8000 ms to retry
```

**Comment by jadamcrain** [comment]
I doesn't look like there's a Tokio (async) equivalent of [std::net::TcpStream::connect_timeout](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.connect_timeout).

I found a stack overflow post though where one of the Tokio maintainer suggests the following:

"Regarding tokio::net::TcpStream, it does not have a dedicated method because all async operations, including connect, can be given a timeout using [tokio::time::timeout](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html)" – [Alice Ryhl](https://stackoverflow.com/users/1704411/alice-ryhl)

This is the way we can add it so that the timeout doesn't depend on the default OS connect timeout. Just like [#245](https://github.com/stepfunc/dnp3/issues/245) though, backwards compatibility will be the concern.

**Comment by jadamcrain** [comment]
Added in https://github.com/stepfunc/dnp3/pull/254
