### ISSUE TITLE
Master freeze operations

### ISSUE THREAD

**Issue by jadamcrain** [stepfunc/dnp3#262]
The outstation supports `ImmediateFreeze` (0x07) and `Freeze-and-clear` (0x09) and their broadcast variants 0x08 and 0x10.

Not supporting sending these was an oversight. Level 4 has the following requirements:

![image](https://user-images.githubusercontent.com/305813/208727956-bab56259-2190-44c9-b7e4-6c0947962429.png)

Beyond level 4, there is the `FreezeAtTime` function which allows the master to specify schedule freeze operations on the master but this doesn't seem to be commonly supported.

![image](https://user-images.githubusercontent.com/305813/208728981-cd506705-ee6d-4953-addc-3aa2c4b587f9.png)

@kevinherron Can you clarify if you also need the freeze-at-time?

**Comment by kevinherron** [comment]
We currently support issuing freeze-at-time from our master, but I don't have any data on whether it's actually used by customers. I couldn't say whether or not having support for freeze-at-time in our new driver will matter without shipping it and seeing if anyone complains or doing an incomplete survey of a few customers. 

We somehow omitted freeze-clear support and that turns out to be the one we get requests for.

**Comment by jadamcrain** [comment]
I'll add it then, pretty easy to do.

**Comment by kevinherron** [comment]
Wish I had the kind of data telemetry gives you without actually having to have telemetry 🙃

**Comment by jadamcrain** [comment]
Completed in https://github.com/stepfunc/dnp3/pull/263
