### ISSUE TITLE
Support all control operations (function codes)

### ISSUE THREAD

**Issue by cdurkin** [stepfunc/dnp3#371]
Currently enum CommandMode only has 2 options DirectOperate & SelectBeforeOperate.

I'm using this library (with C# FFI) to build a DNP3 test harness and hence need access to the other DNP3 function codes for controls i.e. Select, Operate and DirectOperateNoAck. A SelectBeforeOperate option is useful but I need the individual Select and Operate options (and all relevant DNP3 function codes) to be able to send these to an RTU under test.

Thanks

**Comment by jadamcrain** [comment]
Hi @cdurkin .   Adding support for DO NoAck in the master API is something we'd consider adding as the outstation already supports it.  Doing selects without an Operate is not, let me explain...

The API of this library only allows you to do conformant behaviors by design. It is not suitable for testing how another implementation reacts to doing non-conformant things.  When testing our own library, we use a [lower-level test harness](https://github.com/stepfunc/dnp4s) written in Scala. This library implements the full level 2 conformance test procedures that we run in CI. It provides the lower-level ability to script complex non-conformant interactions. It can even do things like sending incorrect CRC values, etc.

**Comment by cdurkin** [comment]
Thanks for the quick response, that's fair enough if the library is not intended exactly for the purpose i'm using it, i will have a look at the low-level test harness you mention, the link in comment above doesn't seem to work but i assume you are referring to these scala files in your repo 'conformance/src/main/scala/io/stepfunc/conformance/dnp3'?

I was much more interested in being able to do the separate select and operate than the DO NoAck so i'll close this issue based on your response.

Thanks again

**Comment by jadamcrain** [comment]
@cdurkin Ah, I just realized that the `dnp4s` repo is private. The scala code you found is just the driver code for it. I'll look into getting an open source license put on it and opening that up.

**Comment by cdurkin** [comment]
that would be great, thanks very much
